from decimal import Decimal
from .dynamo import get_table

# ── original 20 hand-crafted products ────────────────────────────────────────

_BASE_PRODUCTS = [
    {"productId": "P001", "name": "Wireless Headphones", "category": "Electronics", "price": Decimal("79.99"), "stock": 50, "description": "Over-ear noise-cancelling headphones"},
    {"productId": "P002", "name": "Mechanical Keyboard", "category": "Electronics", "price": Decimal("129.99"), "stock": 30, "description": "TKL layout, Cherry MX switches"},
    {"productId": "P003", "name": "USB-C Hub", "category": "Electronics", "price": Decimal("39.99"), "stock": 100, "description": "7-in-1 hub with HDMI, USB-A, SD card"},
    {"productId": "P004", "name": "Webcam 1080p", "category": "Electronics", "price": Decimal("59.99"), "stock": 45, "description": "Full HD webcam with built-in mic"},
    {"productId": "P005", "name": "Monitor Stand", "category": "Electronics", "price": Decimal("34.99"), "stock": 60, "description": "Adjustable aluminum monitor riser"},
    {"productId": "P006", "name": "Running Shoes", "category": "Clothing", "price": Decimal("89.99"), "stock": 80, "description": "Lightweight trail running shoes"},
    {"productId": "P007", "name": "Denim Jacket", "category": "Clothing", "price": Decimal("49.99"), "stock": 40, "description": "Classic blue denim jacket"},
    {"productId": "P008", "name": "Cotton T-Shirt", "category": "Clothing", "price": Decimal("19.99"), "stock": 200, "description": "Organic cotton, crew neck"},
    {"productId": "P009", "name": "Wool Sweater", "category": "Clothing", "price": Decimal("69.99"), "stock": 35, "description": "Merino wool, slim fit"},
    {"productId": "P010", "name": "Cargo Pants", "category": "Clothing", "price": Decimal("44.99"), "stock": 55, "description": "Multi-pocket utility pants"},
    {"productId": "P011", "name": "Clean Code", "category": "Books", "price": Decimal("34.99"), "stock": 25, "description": "Robert C. Martin — software craftsmanship"},
    {"productId": "P012", "name": "Designing Data-Intensive Applications", "category": "Books", "price": Decimal("44.99"), "stock": 20, "description": "Martin Kleppmann — distributed systems"},
    {"productId": "P013", "name": "The Pragmatic Programmer", "category": "Books", "price": Decimal("29.99"), "stock": 30, "description": "Hunt & Thomas — developer career guide"},
    {"productId": "P014", "name": "System Design Interview", "category": "Books", "price": Decimal("24.99"), "stock": 40, "description": "Alex Xu — Vol. 1 & 2"},
    {"productId": "P015", "name": "Deep Work", "category": "Books", "price": Decimal("14.99"), "stock": 50, "description": "Cal Newport — focused success"},
    {"productId": "P016", "name": "Desk Lamp", "category": "Home", "price": Decimal("29.99"), "stock": 70, "description": "LED desk lamp with USB charging port"},
    {"productId": "P017", "name": "Coffee Maker", "category": "Home", "price": Decimal("49.99"), "stock": 25, "description": "12-cup programmable coffee maker"},
    {"productId": "P018", "name": "Air Purifier", "category": "Home", "price": Decimal("89.99"), "stock": 20, "description": "HEPA filter, 500 sq ft coverage"},
    {"productId": "P019", "name": "Throw Blanket", "category": "Home", "price": Decimal("24.99"), "stock": 90, "description": "Soft fleece, 50x60 inches"},
    {"productId": "P020", "name": "Bamboo Cutting Board", "category": "Home", "price": Decimal("19.99"), "stock": 110, "description": "Extra-large with juice groove"},
]

# ── 80 generated products (20 per category, IDs P021–P100) ───────────────────

_ELECTRONICS_NAMES = [
    ("Bluetooth Speaker", "Portable, waterproof, 20h battery"),
    ("Smart Watch", "Health tracking, GPS, 5-day battery"),
    ("Laptop Stand", "Foldable aluminum, adjustable height"),
    ("LED Strip Lights", "RGB, WiFi, 5m roll"),
    ("Portable Charger", "20000mAh, dual USB-C"),
    ("Noise-Cancelling Earbuds", "ANC, 30h total battery"),
    ("4K Webcam", "Auto-focus, built-in ring light"),
    ("Gaming Mouse", "16000 DPI, 7 programmable buttons"),
    ("Wireless Charger Pad", "15W fast charge, Qi compatible"),
    ("HDMI Capture Card", "4K60 passthrough, USB-C"),
    ("USB Microphone", "Cardioid condenser, plug-and-play"),
    ("Smart Plug", "WiFi, energy monitoring, voice control"),
    ("E-Reader", "6-inch glare-free display, 6-week battery"),
    ("Keyboard Wrist Rest", "Memory foam, non-slip base"),
    ("Screen Cleaning Kit", "Microfiber cloth + spray, 100ml"),
    ("Cable Management Box", "Hides power strip and cables"),
    ("Mini PC", "Intel N100, 8GB RAM, 256GB SSD"),
    ("Portable SSD", "2TB, USB 3.2 Gen2, 1050 MB/s"),
    ("Drawing Tablet", "8x5 inch, 8192 pressure levels"),
    ("Smart Doorbell", "1080p, motion detection, cloud storage"),
]

_CLOTHING_NAMES = [
    ("Hoodie", "Heavyweight fleece, kangaroo pocket"),
    ("Chino Shorts", "Stretch cotton, 7-inch inseam"),
    ("Polo Shirt", "Pique cotton, slim fit"),
    ("Waterproof Jacket", "3-layer shell, packable"),
    ("Compression Leggings", "High-waist, 4-way stretch"),
    ("Casual Sneakers", "Canvas upper, rubber sole"),
    ("Beanie", "Ribbed knit, one size fits all"),
    ("Oxford Shirt", "Non-iron cotton, button-down collar"),
    ("Athletic Shorts", "Quick-dry, 5-inch inseam"),
    ("Puffer Vest", "Recycled fill, side pockets"),
    ("Swim Trunks", "Quick-dry, mesh liner, 7-inch"),
    ("Flannel Shirt", "100% cotton, relaxed fit"),
    ("Yoga Pants", "4-way stretch, high-rise"),
    ("Leather Belt", "Full-grain, reversible black/brown"),
    ("Crew Socks 6-Pack", "Cushioned sole, moisture-wicking"),
    ("Baseball Cap", "Structured, adjustable strap"),
    ("Slim Fit Chinos", "Stretch, wrinkle-resistant"),
    ("Tank Top 3-Pack", "Cotton-modal blend, ribbed"),
    ("Winter Gloves", "Touchscreen-compatible, fleece lining"),
    ("Dress Socks 5-Pack", "Mercerized cotton, reinforced heel"),
]

_BOOKS_NAMES = [
    ("The Art of Computer Programming", "Knuth — 4 vol. fundamental algorithms"),
    ("Introduction to Algorithms", "CLRS — 4th edition"),
    ("Refactoring", "Martin Fowler — 2nd edition"),
    ("Site Reliability Engineering", "Google SRE book"),
    ("The Phoenix Project", "DevOps novel by Gene Kim"),
    ("Accelerate", "Forsgren et al. — DevOps metrics"),
    ("Domain-Driven Design", "Eric Evans — the blue book"),
    ("Release It!", "Nygard — production-ready software"),
    ("The Staff Engineer's Path", "Tanya Reilly"),
    ("An Elegant Puzzle", "Will Larson — engineering management"),
    ("Software Architecture Patterns", "Mark Richards — O'Reilly"),
    ("Kubernetes in Action", "Marko Luksa — 2nd edition"),
    ("Database Internals", "Alex Petrov — storage engines"),
    ("Distributed Systems", "van Steen & Tanenbaum — 4th ed"),
    ("The Manager's Path", "Camille Fournier"),
    ("A Philosophy of Software Design", "John Ousterhout — 2nd ed"),
    ("Effective Java", "Joshua Bloch — 3rd edition"),
    ("Python Cookbook", "Beazley & Jones — recipes"),
    ("High Performance Python", "Micha Gorelick & Ian Ozsvald"),
    ("Fluent Python", "Luciano Ramalho — 2nd edition"),
]

_HOME_NAMES = [
    ("French Press", "Stainless steel, 34oz, double-walled"),
    ("Wooden Spice Rack", "Holds 20 jars, wall-mounted"),
    ("Blackout Curtains", "100% polyester, noise-reducing"),
    ("Humidifier", "Ultrasonic, 4L tank, whisper-quiet"),
    ("Under-Desk Drawer", "Clamp-on, holds keyboard and more"),
    ("Bedside Organizer", "Hanging caddy, 6 pockets"),
    ("Shower Caddy", "Rust-proof stainless, 3 shelves"),
    ("Laundry Hamper", "Collapsible, 55L, bamboo frame"),
    ("Smart Thermostat", "WiFi, learning schedule, energy report"),
    ("Electric Kettle", "1.7L, 60min keep-warm, variable temp"),
    ("Vegetable Chopper", "14-piece set, dishwasher safe"),
    ("Silicone Baking Mats 2-Pack", "Non-stick, fits half-sheet pan"),
    ("Bamboo Bath Mat", "Anti-slip, moisture-resistant"),
    ("Candle Set 3-Pack", "Soy wax, 50h burn each"),
    ("Door Draft Stopper", "Self-adhesive foam seal, 36-inch"),
    ("Magnetic Knife Strip", "Stainless steel, holds 8 knives"),
    ("Pot and Pan Organizer", "Adjustable rack, 9 dividers"),
    ("Shower Squeegee", "Stainless handle, rubber blade"),
    ("Over-Door Hooks 6-Pack", "No-drill, holds 22 lbs each"),
    ("Wax Melter", "Electric, ceramic dish, 25W"),
]

# ── 400 generated products (100 per category, IDs P101–P500) ─────────────────

_SPORTS_NAMES = [
    ("Yoga Mat", "6mm thick, non-slip, carry strap included"),
    ("Resistance Bands Set", "5 levels, latex-free, door anchor"),
    ("Dumbbells 5lb Pair", "Neoprene coated, hex head"),
    ("Dumbbells 10lb Pair", "Neoprene coated, hex head"),
    ("Dumbbells 20lb Pair", "Cast iron, rubber end caps"),
    ("Kettlebell 16kg", "Cast iron, powder-coated"),
    ("Jump Rope", "Speed cable, adjustable length, ball bearings"),
    ("Pull-Up Bar", "Doorframe, no-screw, 300lb capacity"),
    ("Foam Roller", "High-density, 36-inch, smooth surface"),
    ("Ab Wheel", "Dual-wheel, non-slip handles, knee pad"),
    ("Push-Up Handles", "Rotating grips, 360° rotation"),
    ("Gym Gloves", "Padded palm, wrist wrap, breathable"),
    ("Lifting Belt", "4-inch nylon, Velcro, lever buckle"),
    ("Weightlifting Shoes", "0.6-inch heel lift, metatarsal strap"),
    ("Running Shorts", "2-in-1 liner, 5-inch, reflective strips"),
    ("Compression Socks", "Graduated 15-20 mmHg, calf support"),
    ("Sports Bra", "High-impact, underwire-free, racerback"),
    ("Gym Bag", "40L duffel, wet/dry compartment, shoe pocket"),
    ("Water Bottle 32oz", "Vacuum insulated, leak-proof, straw lid"),
    ("Protein Shaker", "700ml, leak-proof, stainless mixing ball"),
    ("Tennis Racket", "Graphite, 300g, pre-strung"),
    ("Tennis Balls 3-Pack", "Extra duty felt, tournament grade"),
    ("Badminton Set", "4 rackets, 3 shuttlecocks, carry bag"),
    ("Ping Pong Paddles Set", "2 paddles, 3 balls, carry case"),
    ("Basketball", "Size 7, indoor/outdoor rubber cover"),
    ("Soccer Ball", "Size 5, machine-stitched, thermally bonded"),
    ("Football", "Composite leather, official size/weight"),
    ("Volleyball", "Indoor/outdoor, soft PU cover"),
    ("Frisbee", "175g, ultimate disc, WFDF approved"),
    ("Hiking Poles", "Collapsible, carbon fiber, wrist straps"),
    ("Hiking Backpack 30L", "Rain cover, hip belt, hydration sleeve"),
    ("Trekking Gaiters", "Waterproof, front zip, crampon compatible"),
    ("Climbing Harness", "Padded waist, adjustable leg loops"),
    ("Carabiner Set", "5-pack, locking, 25kN rating"),
    ("Sleeping Bag", "0°C comfort, 800g fill, compression sack"),
    ("Camping Hammock", "Nylon, 400lb capacity, tree straps"),
    ("Portable Camp Stove", "Dual-burner, 10000 BTU, carry case"),
    ("Fishing Rod", "7-foot, medium action, graphite blank"),
    ("Tackle Box", "3-tray, waterproof, 80 compartments"),
    ("Snorkel Set", "Dry-top snorkel, tempered lens mask, fins"),
    ("Swim Goggles", "Anti-fog, UV protection, 5 nose bridges"),
    ("Swim Cap", "Silicone, wrinkle-free, unisex"),
    ("Pool Float", "Inflatable, 180x90cm, cup holders"),
    ("Cycling Helmet", "MIPS, 20 vents, adjustable fit dial"),
    ("Bike Lock", "U-lock + cable, 14mm shackle"),
    ("Cycling Gloves", "Gel padded, half-finger, touchscreen tips"),
    ("Cycling Jersey", "Moisture-wicking, 3 rear pockets, UPF 50"),
    ("Bike Pump", "Floor pump, 160 PSI, Presta/Schrader"),
    ("Bike Lights Set", "Front 800lm + rear 100lm, USB rechargeable"),
    ("Skateboard", "7-ply maple, 52mm wheels, ABEC-7 bearings"),
    ("Roller Blades", "Adjustable 4-size, 72mm inline wheels"),
    ("Knee Pads", "EVA foam, breathable, adjustable straps"),
    ("Elbow Pads", "Hard shell, moisture-wicking liner"),
    ("Wrist Guards", "Splint support, fingerless, pair"),
    ("Boxing Gloves", "12oz, hook-and-loop, PU leather"),
    ("Speed Bag", "Pear-shaped, genuine leather, swivel mount"),
    ("Punching Bag", "70lb heavy bag, chain, hand wraps"),
    ("Mouth Guard", "Boil-and-bite, BPA-free, case included"),
    ("Agility Cones Set", "20-pack, 9-inch, 5 colors"),
    ("Speed Ladder", "20-foot, 11 rungs, carry bag"),
    ("Resistance Tube", "Door anchor, handles, ankle straps"),
    ("Ankle Weights", "1lb each, adjustable, pair"),
    ("Balance Board", "Wobble board, 360° tilt, non-slip"),
    ("Bosu Ball", "65cm, pump included, 300lb capacity"),
    ("Medicine Ball 6lb", "Rubber, textured grip, dual-color"),
    ("Battle Rope", "1.5-inch, 30-foot, poly dacron"),
    ("Pull-Up Assist Band", "41-inch loop, heavy resistance, latex"),
    ("Dip Station", "Freestanding, padded handles, 300lb"),
    ("Gymnastic Rings", "Wood, 28mm diameter, 4.5m straps"),
    ("Rowing Machine", "Magnetic resistance, 8 levels, folding"),
    ("Treadmill Mat", "6mm PVC, 80x150cm, reduces vibration"),
    ("Yoga Block Set", "2 blocks + strap, EVA foam, cork texture"),
    ("Yoga Strap", "8-foot, D-ring buckle, 6 colors"),
    ("Pilates Ring", "15-inch, dual grip pads, 14lb resistance"),
    ("Golf Balls 12-Pack", "2-piece, surlyn cover, 330 dimples"),
    ("Golf Glove", "Cabretta leather palm, velcro closure"),
    ("Golf Tees 100-Pack", "2.75-inch, biodegradable wood"),
    ("Archery Target", "60x60cm, layered foam, target face"),
    ("Dart Board", "Sisal fiber, staple-free bullseye, cabinet"),
    ("Bocce Ball Set", "8 resin balls, pallino, carry bag"),
    ("Cornhole Set", "2 boards, 8 bags, regulation size"),
    ("Horseshoe Set", "4 horseshoes + 2 stakes, carry bag"),
    ("Croquet Set", "6-player, hardwood mallets, wickets, carry bag"),
    ("Badminton Shuttlecocks", "12-pack, feather, indoor grade"),
    ("Table Tennis Net", "Clip-on, adjustable tension, 5-foot"),
    ("Cricket Bat", "Kashmir willow, full size, oil finish"),
    ("Rugby Ball", "Gilbert, match ball, size 5"),
    ("Lacrosse Stick", "Complete stick, mid-pocket mesh head"),
    ("Hockey Puck", "Vulcanized rubber, 6oz, official size"),
    ("Ski Goggles", "OTG, anti-fog, spherical lens, UV400"),
    ("Ski Gloves", "Waterproof, insulated, wrist leash"),
    ("Ski Helmet", "MIPS, BOA fit, 13 vents"),
    ("Snowboard Bag", "166cm, padded, wheels, lockable"),
    ("Surf Wax", "Tropical formula, 3-pack"),
    ("Rashguard", "UPF 50+, long sleeve, flatlock seams"),
    ("Wetsuit", "3/2mm, back zip, thermal lining"),
    ("Kayak Paddle", "Fiberglass blade, aluminum shaft, 220cm"),
    ("Life Jacket", "USCG Type III, foam core, zippered"),
    ("Yoga Towel", "Microfiber, non-slip grip dots, 61x183cm"),
    ("Exercise Mat", "10mm thick, HIIT/pilates, carrying strap"),
]

_KITCHEN_NAMES = [
    ("Cast Iron Skillet 10-inch", "Pre-seasoned, oven-safe to 500°F"),
    ("Non-Stick Frying Pan", "12-inch, PFOA-free, induction compatible"),
    ("Stainless Steel Pot Set", "10-piece, tri-ply, dishwasher safe"),
    ("Wok 14-inch", "Carbon steel, flat bottom, wooden handle"),
    ("Dutch Oven 6qt", "Enameled cast iron, oven-safe to 500°F"),
    ("Baking Sheet Pan", "Half-sheet, aluminized steel, non-stick"),
    ("Muffin Tin 12-cup", "Non-stick, standard size, carbon steel"),
    ("Loaf Pan", "9x5 inch, non-stick, silicone handles"),
    ("Pie Dish", "9-inch, ceramic, fluted edge"),
    ("Springform Pan", "9-inch, leak-proof latch, removable base"),
    ("Stand Mixer", "5.5qt bowl, 10-speed, 3 attachments"),
    ("Hand Mixer", "5-speed, 275W, turbo boost"),
    ("Food Processor", "12-cup, 700W, 3 blades"),
    ("Blender", "64oz, 1450W, tamper included"),
    ("Immersion Blender", "500W, variable speed, BPA-free"),
    ("Rice Cooker", "10-cup, fuzzy logic, keep-warm"),
    ("Pressure Cooker", "6qt, 14 safety mechanisms, stainless"),
    ("Slow Cooker", "7qt, oval, 3 heat settings, locking lid"),
    ("Air Fryer", "5.8qt, digital, 8 presets, non-stick basket"),
    ("Toaster Oven", "0.9 cu ft, convection, 9 functions"),
    ("Waffle Maker", "Round, 4-square Belgian, non-stick plates"),
    ("Panini Press", "1000W, floating hinge, drip tray"),
    ("Electric Griddle", "12x22 inch, 1500W, removable drip tray"),
    ("Espresso Machine", "15 bar, manual frother, 1.8L tank"),
    ("Drip Coffee Maker", "12-cup, brew strength control, thermal carafe"),
    ("Cold Brew Maker", "1.5L, fine-mesh filter, airtight lid"),
    ("Tea Kettle", "1.7L stainless, stovetop, whistle"),
    ("Milk Frother", "Electric, hot/cold, 250ml"),
    ("Wine Opener", "Electric, foil cutter, 2 extra batteries"),
    ("Bottle Opener", "Wall-mounted, cast iron, cap catcher"),
    ("Can Opener", "Smooth edge, magnetic lid lifter, stainless"),
    ("Vegetable Peeler", "Y-peeler, ceramic blade, non-slip"),
    ("Mandoline Slicer", "5 blades, cut-resistant glove, folding"),
    ("Box Grater", "4-sided, non-slip, storage container"),
    ("Microplane Zester", "Extra coarse, soft-grip handle"),
    ("Colander 5qt", "Stainless, micro-perforated, handle+feet"),
    ("Mixing Bowls Set", "5-piece, nesting, non-slip base, lids"),
    ("Measuring Cups Set", "7-piece, stainless, engraved markings"),
    ("Measuring Spoons Set", "6-piece, stainless, double-sided"),
    ("Silicone Spatula Set", "3-piece, heat-resistant to 600°F"),
    ("Wooden Spoon Set", "6-piece, acacia wood, various sizes"),
    ("Whisk Set", "3-piece, stainless, silicone handles"),
    ("Tongs 12-inch", "Silicone tips, locking, heat-resistant"),
    ("Ladle", "13-inch, stainless, pour spout"),
    ("Slotted Spoon", "13-inch, stainless, large drainage holes"),
    ("Pasta Fork", "Stainless, heat-resistant, noodle tines"),
    ("Spider Strainer", "6-inch basket, bamboo handle"),
    ("Pastry Brush", "Silicone, heat-safe, wide 1.5-inch"),
    ("Rolling Pin", "Marble, 10-inch, wooden handles"),
    ("Dough Scraper", "Stainless + silicone combo, 2-pack"),
    ("Kitchen Scale", "0.1g precision, tare, 11lb capacity"),
    ("Meat Thermometer", "Instant-read, 2-second, backlit"),
    ("Candy Thermometer", "Clip-on, 100°F–400°F, stainless"),
    ("Oven Thermometer", "Dial type, 100°F–600°F, oven-safe"),
    ("Instant-Read Thermometer", "Foldable, waterproof, 3-second"),
    ("Food Storage Containers Set", "20-piece, BPA-free, airtight, stackable"),
    ("Glass Meal Prep Containers", "10-piece, borosilicate, snap-lock lids"),
    ("Mason Jars 12-Pack", "Wide mouth, 16oz, lids + bands"),
    ("Vacuum Sealer", "5-meter roll + 10 bags, moist/dry mode"),
    ("Zip-Lock Bags 100-Pack", "Gallon size, BPA-free, double zipper"),
    ("Aluminum Foil Heavy Duty", "200 sq ft, 18-inch wide"),
    ("Parchment Paper Roll", "100 sq ft, unbleached, non-stick"),
    ("Dish Rack", "2-tier, stainless, removable drip tray"),
    ("Dish Brush", "Long handle, replaceable head, firm bristle"),
    ("Dish Soap Dispenser", "12oz, countertop pump, stainless"),
    ("Sponge Holder", "Sink caddy, suction cup, drainage slots"),
    ("Pot Holders Set", "2-pack, silicone, 500°F rated"),
    ("Oven Mitts Set", "2 pair, quilted cotton, 14-inch"),
    ("Kitchen Timer", "Magnetic, digital, count up/down"),
    ("Magnetic Spice Jars Set", "20 jars, chalkboard labels, fridge-safe"),
    ("Oil Dispenser", "17oz, borosilicate glass, stainless spout"),
    ("Salt and Pepper Mill Set", "Adjustable coarseness, acrylic, pair"),
    ("Mortar and Pestle", "4-cup, granite, rough interior"),
    ("Herb Stripper", "5-hole stainless, dishwasher safe"),
    ("Avocado Slicer", "3-in-1: split/pit/slice, BPA-free"),
    ("Apple Corer", "Stainless, dishwasher safe, 8-wedge"),
    ("Strawberry Huller", "Twist design, BPA-free, set of 3"),
    ("Cherry Pitter", "Single, stainless, splatter guard"),
    ("Garlic Press", "Squeeze and turn, self-cleaning, stainless"),
    ("Citrus Juicer", "Manual press, dual-sided, 2.5-cup pitcher"),
    ("Salad Spinner", "5qt, one-press pump, non-slip base"),
    ("Bread Box", "Bamboo + linen, hinged lid, 13-inch"),
    ("Cake Stand", "12-inch, marble pattern, dome lid"),
    ("Pie Server", "Stainless, serrated edge, gift box"),
    ("Cake Slicer", "Offset spatula 9-inch + 4-inch set"),
    ("Ice Cream Scoop", "Squeeze handle, stainless, dishwasher safe"),
    ("Cookie Scoop", "1-tablespoon, trigger release, stainless"),
    ("Pizza Cutter", "Rocker blade, 14-inch, protective cover"),
    ("Cheese Grater", "6-sided, box style, non-slip, 4 surfaces"),
    ("Butter Dish", "Ceramic, covered, fits standard butter"),
    ("Egg Separator", "Suction base, yolk separator + whites"),
    ("Egg Timer", "Soft/med/hard indicator, no battery"),
    ("Deviled Egg Tray", "24-slot, lid, carrier handle"),
    ("Sushi Rolling Mat", "Bamboo, 9.5-inch, 2-pack with rice paddle"),
    ("Dumpling Mold", "Set of 3 sizes, BPA-free, press seal"),
    ("Cookie Cutters Set", "20-piece, stainless, holiday shapes"),
    ("Cake Decorating Set", "48-piece, tips, couplers, bags"),
    ("Piping Bags Set", "100 disposable + 5 tips, BPA-free"),
    ("Instant Pot Liner", "6qt, stainless, compatible with IP Duo"),
    ("Silicone Egg Mold", "6-cavity, oven/microwave safe, non-stick"),
]

_BEAUTY_NAMES = [
    ("Retinol Face Serum", "0.3% encapsulated retinol, squalane base"),
    ("Vitamin C Serum", "15% L-ascorbic acid, ferulic acid, vit E"),
    ("Hyaluronic Acid Serum", "3 molecular weights, 2% HA"),
    ("Niacinamide Serum", "10% niacinamide + 1% zinc"),
    ("Glycolic Acid Toner", "7% glycolic, aloe vera, witch hazel"),
    ("Salicylic Acid Toner", "2% BHA, pore-minimising, oil-free"),
    ("Rose Water Toner", "100% pure, hydrating, alcohol-free"),
    ("Micellar Water", "400ml, no-rinse, sensitive skin formula"),
    ("Facial Cleanser Foaming", "Gentle, fragrance-free, 6.5 fl oz"),
    ("Gentle Face Wash", "Cream cleanser, hydrating, ceramides"),
    ("Exfoliating Scrub", "AHA + walnut powder, brightening"),
    ("Clay Face Mask", "Kaolin + charcoal, pore cleansing, 100ml"),
    ("Sheet Mask 10-Pack", "Collagen + hyaluronic, 25ml per mask"),
    ("Eye Cream", "Caffeine + vitamin K, reduces dark circles"),
    ("Night Cream", "Peptides, ceramides, 50ml"),
    ("Day Moisturizer SPF30", "Lightweight, non-greasy, broad spectrum"),
    ("BB Cream SPF20", "Tinted, medium coverage, 8 shades"),
    ("CC Cream", "Color-correcting, hydrating, buildable"),
    ("Sunscreen SPF50", "PA++++, ultra-light, water-resistant 80min"),
    ("Lip Balm 3-Pack", "SPF 15, shea butter, 3 flavors"),
    ("Lip Mask", "Overnight, peptides, vanilla scent, 20g"),
    ("Lip Plumper", "Hyaluronic filler, gloss finish, 4 shades"),
    ("Foundation Brush", "Flat kabuki, synthetic bristles, dense"),
    ("Contour Brush", "Angled, tapered, cruelty-free"),
    ("Blush Brush", "Dome-shaped, natural hair blend"),
    ("Eyeshadow Brush Set", "12-piece, synthetic, zip pouch"),
    ("Kabuki Brush", "Buffing, ultra-dense, handle-shaped"),
    ("Beauty Blender Sponge", "Micro-foam, latex-free, dual-use"),
    ("Makeup Setting Spray", "100ml, long-lasting, dewy finish"),
    ("Primer Stick", "Pore-filling, vitamin E, twist-up"),
    ("Highlighter Palette", "4-shade, pressed powder, mirror"),
    ("Blush Palette", "6-shade, matte + shimmer, pan size"),
    ("Eyeshadow Palette", "18-shade, warm neutrals, cruelty-free"),
    ("Contour Kit", "3 shades: highlight / bronze / blush"),
    ("Mascara", "Lengthening + volumizing, no flaking, 10ml"),
    ("Liquid Eyeliner", "Felt tip, waterproof, 24h wear"),
    ("Kohl Eyeliner", "Creamy, smudgeable, built-in sharpener"),
    ("Eyebrow Pencil", "Micro-precision, 4 shades, spoolie end"),
    ("Brow Gel", "Tinted, flexible hold, waterproof"),
    ("Eyebrow Powder Kit", "3-shade palette, angled brush, mirror"),
    ("Nude Lipstick", "Creamy, long-wear, moisturizing, 10 shades"),
    ("Red Lipstick", "Matte, bold pigment, 8h wear"),
    ("Lip Liner", "Retractable, smear-proof, 12 shades"),
    ("Lip Gloss Set", "6 shades, plumping, non-sticky"),
    ("Nail Polish Set 12-Pack", "Quick-dry, gel-like finish, chip-resist"),
    ("Gel Nail Polish Kit", "36W lamp + 6 colors + top/base coat"),
    ("Nail File Set", "Crystal, 4-pack, washable, fine grit"),
    ("Cuticle Oil", "10ml pen, jojoba + vitamin E, sweet almond"),
    ("Nail Strengthener", "Formaldehyde-free, keratin formula, 15ml"),
    ("Press-On Nails Set", "24 nails, almond shape, adhesive tabs"),
    ("Shampoo Volumizing", "Biotin + collagen, sulfate-free, 300ml"),
    ("Conditioner Moisturizing", "Argan oil, detangling, 300ml"),
    ("Hair Mask", "Keratin + coconut oil, repair, 200ml"),
    ("Leave-In Conditioner", "Spray, heat-protective, detangling"),
    ("Hair Oil", "Moroccan argan, frizz-free, 100ml"),
    ("Dry Shampoo", "Volumizing, invisible formula, 150ml"),
    ("Heat Protectant Spray", "250°C protection, humidity shield, 200ml"),
    ("Hair Mousse", "Medium hold, non-crunchy, curl-defining"),
    ("Strong Hold Hair Gel", "Alcohol-free, no flake, 250ml"),
    ("Pomade", "Water-based, high shine, medium hold, 100g"),
    ("Hair Wax", "Matte finish, flexible hold, 75g"),
    ("Edge Control Gel", "Castor oil, 24h hold, humidity-resistant"),
    ("Boar Bristle Brush", "100% boar, cushion base, smoothing"),
    ("Wide Tooth Comb", "Anti-static, seamless, detangle wet hair"),
    ("Detangling Brush", "FlexiSoft bristles, works wet or dry"),
    ("Silk Scrunchies Set", "5-pack, 22 momme, no crease"),
    ("Hair Clips Set", "20-pack, claw clips, assorted sizes"),
    ("Bobby Pins 200-Pack", "Wave tip, non-slip, grip coating"),
    ("Satin Pillowcase", "Queen size, 19 momme, zipper closure"),
    ("Hair Towel Wrap", "Microfiber, button fastening, 2-pack"),
    ("Facial Roller Jade", "Dual-ended, natural jade, anti-puff"),
    ("Gua Sha Stone", "Rose quartz, curved edge, face + neck"),
    ("Face Massager Electric", "T-bar vibration, 5 speeds, USB charge"),
    ("Blackhead Remover Tool", "Stainless, 5-piece comedone extractor set"),
    ("Pore Strips 30-Pack", "Charcoal, nose strips, blackhead clear"),
    ("Eye Patches 60-Pack", "Collagen + gold, 30 pairs, anti-wrinkle"),
    ("Lip Scrub", "Brown sugar + coconut oil, exfoliating, 30g"),
    ("Face Mist Spray", "Thermal water, soothing, 150ml"),
    ("After-Sun Lotion", "Aloe vera 70%, cooling gel, 200ml"),
    ("Self-Tanner Lotion", "Medium-dark, streak-free, 200ml"),
    ("Body Scrub", "Coffee + coconut, exfoliating, 200g"),
    ("Body Lotion Unscented", "Shea butter + ceramides, fragrance-free, 400ml"),
    ("Shea Butter Cream", "100% raw, unrefined, 200g"),
    ("Stretch Mark Cream", "Vitamin E + centella, 200ml"),
    ("Deodorant Stick", "Aluminum-free, 48h, baking soda formula"),
    ("Roll-On Perfume", "10ml, oil-based, travel-size, 5 scents"),
    ("Body Spray", "250ml, long-lasting, floral musk"),
    ("Reed Diffuser", "200ml, 8 reeds, 90-day scent throw"),
    ("Cologne 50ml", "EDT, woody citrus, spray bottle"),
    ("Eau de Parfum 50ml", "EDP, floral oriental, 8h longevity"),
    ("Electric Face Cleanser", "Sonic, 2 speeds, magnetic charger"),
    ("Silicone Face Brush", "Manual, soft bristle, 2-sided"),
    ("Dermaplaning Tool", "Stainless, 10-blade refill, non-irritating"),
    ("Lash Curler", "Soft pad, spring action, travel size"),
    ("Tweezers Set", "4-piece: slant, point, flat, ingrown"),
    ("Nail Clippers Set", "5-piece, stainless, file + pusher"),
    ("Razor Multi-Pack", "5-blade, aloe strip, 8 cartridges"),
    ("Shaving Cream", "Sensitive, glycerin, 200ml tube"),
    ("Aftershave Balm", "Alcohol-free, cooling, 100ml"),
    ("Men's Grooming Kit", "8-piece: clippers, trimmer, comb, case"),
]

_OFFICE_NAMES = [
    ("Ballpoint Pens 12-Pack", "Medium 1.0mm, black ink, smooth write"),
    ("Gel Pens 10-Pack", "0.5mm, quick-dry, assorted colors"),
    ("Rollerball Pens 5-Pack", "0.7mm, archival ink, cap style"),
    ("Fountain Pen", "Fine nib, converter included, stainless"),
    ("Mechanical Pencil Set", "0.5mm + 0.7mm, HB leads, 12 refills"),
    ("Colored Pencils 48-Pack", "Soft core, blendable, wax-based"),
    ("Markers 24-Pack", "Dual-tip: brush + fine, non-bleed"),
    ("Highlighters 6-Pack", "Chisel tip, fluorescent, non-dry"),
    ("Whiteboard Markers Set", "8 colors, dry-erase, magnetic cap"),
    ("Permanent Markers 12-Pack", "Fine + ultra-fine, waterproof"),
    ("Sticky Notes 12-Pack", "3x3 inch, 90 sheets each, pastel"),
    ("Sticky Flags 300-Pack", "1-inch, 5 colors, semi-transparent"),
    ("Index Cards 200-Pack", "4x6 inch, ruled, white"),
    ("Notebook A5", "160 pages, dot grid, hardcover, elastic"),
    ("Notebook A4", "200 pages, lined, spiral binding"),
    ("Spiral Notebook", "70 sheets, 3-subject, perforated"),
    ("Hardcover Journal", "192 pages, blank, bookmark ribbon"),
    ("Planner Weekly", "A5, 12-month, hourly, lay-flat binding"),
    ("Desk Calendar", "5x8 inch, daily, stand + easel"),
    ("Appointment Book", "2-column hourly, monthly tabs, pocket"),
    ("Stapler Heavy Duty", "25-sheet, jam-proof, includes 1000 staples"),
    ("Staples 5000-Pack", "26/6, standard, box"),
    ("Staple Remover", "Jaw type, ergonomic, black"),
    ("Hole Punch 3-Ring", "30-sheet, adjustable guide, metal"),
    ("Paper Clips 100-Pack", "Smooth, standard 32mm, silver"),
    ("Binder Clips Set", "60-pack: small/medium/large mix"),
    ("Rubber Bands 200-Pack", "Mixed sizes, natural latex"),
    ("Tape Dispenser", "Desktop, weighted base, fits 1-inch core"),
    ("Clear Tape 6-Pack", "3/4-inch, 27 yards, invisible finish"),
    ("Double-Sided Tape", "1/2-inch, removable, photo-safe"),
    ("Scissors Heavy Duty", "8-inch, stainless, soft grip"),
    ("Letter Opener", "Stainless, safety guard, foam grip"),
    ("Ruler 12-inch", "Clear acrylic, metal edge, mm+inch"),
    ("Protractor Set", "180° + 360°, clear, with ruler"),
    ("T-Square", "18-inch, transparent, inking edge"),
    ("Clipboard Pack of 3", "Letter size, low-profile clip, hardboard"),
    ("Manila Folders 25-Pack", "Letter, 1/3 cut, kraft"),
    ("File Folders Hanging", "25-pack, legal, 1/5 cut, green"),
    ("Accordion File Organizer", "13-pocket, A-Z tabs, snap closure"),
    ("Magazine File 6-Pack", "Metal, open-top, stackable"),
    ("Desk Organizer Tray", "5-compartment, bamboo, stackable"),
    ("Monitor Riser", "Bamboo, 2-shelf, ventilated"),
    ("Document Tray Stackable", "5-tier, metal mesh, label holders"),
    ("Pen Cup", "Weighted metal, 360° rotation, 3.5-inch"),
    ("Business Card Holder", "Aluminum, 96-card, dual-sided display"),
    ("Nameplate Desk", "Engraved acrylic, 9x2.5 inch, black"),
    ("Inbox Tray", "Stackable, letter size, smoke acrylic"),
    ("Cable Organizer Clips", "20-pack, adhesive, silicone, 5 colors"),
    ("Mouse Pad with Wrist Rest", "XL 900x400mm, memory foam, stitched edge"),
    ("Keyboard Cover", "Silicone, universal TKL, washable"),
    ("Laptop Sleeve 15-inch", "Neoprene, dual-zip, handle"),
    ("Laptop Bag 15-inch", "Messenger style, padded, tablet pocket"),
    ("Backpack with USB Port", "30L, anti-theft, external USB charge port"),
    ("Printer Paper A4 500 Sheets", "80gsm, bright white, multi-purpose"),
    ("Photo Paper Glossy", "4x6 inch, 100 sheets, 200gsm"),
    ("Labels 100-Pack", "3x1 inch, white, laser+inkjet compatible"),
    ("Envelopes 50-Pack", "#10, self-seal, 24lb, white"),
    ("Bubble Mailers 25-Pack", "6x10 inch, self-seal, padded"),
    ("Shipping Tape", "2-inch, 110 yards, 6-pack"),
    ("Packing Peanuts", "1 cu ft bag, anti-static, EPS"),
    ("Correction Tape", "5mm x 6m, lateral, smooth coverage"),
    ("White-Out Pen", "Fine tip, fast-dry, 7ml"),
    ("Eraser Set", "3-pack: vinyl, kneaded, gum"),
    ("Pencil Sharpener Electric", "Auto-stop, helical blade, USB or battery"),
    ("Page Magnifier", "7.5x10 inch, 2x lens, flexible neck stand"),
    ("Bookends Pair", "Heavy-duty metal, non-slip, adjustable"),
    ("Book Stand", "Cookbook holder, adjustable angle, page clips"),
    ("Reading Light Clip-On", "3 brightness levels, 360° flex neck, USB"),
    ("USB Desk Fan", "4-inch, 3-speed, silent, 360° tilt"),
    ("Mini Heater", "400W, ceramic, tilt-off safety, compact"),
    ("Air Quality Monitor", "CO2, temp, humidity, color LCD"),
    ("Wireless Keyboard", "Compact, 2.4G + BT, scissor switch"),
    ("Wireless Mouse", "1600 DPI, silent, 3-device BT switch"),
    ("USB Hub 7-Port", "USB 3.0, individual switches, power adapter"),
    ("HDMI Adapter", "USB-C to HDMI 2.0, 4K60, plug-and-play"),
    ("DisplayPort Cable", "1.4, 8K60, 6 feet, gold-plated"),
    ("Extension Cord 6-Outlet", "6 foot, 15A, right-angle plug"),
    ("Surge Protector 8-Outlet", "3000J, coax + ethernet protection"),
    ("Power Strip with USB", "6 outlets + 3 USB-C, 5-foot cord"),
    ("Desk Clock", "Alarm + temp display, silent sweep, wood"),
    ("Digital Timer", "Magnetic, loud alarm, count up/down"),
    ("Calculator Scientific", "2-line display, 240 functions, solar+battery"),
    ("Label Maker", "QWERTY keyboard, 6mm-24mm tape, BT app"),
    ("Laminator", "9-inch width, 3-5 mil, warm-up 4 min"),
    ("Laminator Pouches 100-Pack", "Letter size, 5 mil, clear gloss"),
    ("Paper Shredder", "Micro-cut, 8-sheet, P-4, 30L bin"),
    ("Document Scanner", "Portable, duplex, 25ppm, USB/WiFi"),
    ("Stamp Pad", "Ink-soaked, 3x4 inch, black, fast-dry"),
    ("Self-Inking Stamp Set", "4 common messages, pre-inked, red"),
    ("Push Pins 100-Pack", "Brass head, steel point, cork + foam"),
    ("Magnetic Whiteboard", "18x24 inch, dry-erase + corkboard combo"),
    ("Corkboard", "24x18 inch, natural cork, aluminum frame"),
    ("Whiteboard Eraser", "Magnetic, felt, fits standard ledge"),
    ("Flip Chart Pad", "25 sheets, 27x34 inch, ruled/plain"),
    ("Presentation Clicker", "2.4G, 100m range, red laser, USB-A"),
    ("Laser Pointer", "Green 532nm, 1mW, click+hold mode"),
    ("HDMI Presentation Cable", "HDMI 2.0, 25-foot, flat, in-wall rated"),
    ("Wireless Presenter", "2.4G, countdown timer, 100m range"),
    ("Phone Stand Adjustable", "Aluminum, 0-90°, universal 4-10 inch"),
    ("Tablet Stand", "Aluminum, 3 angles, foldable, 7-13 inch"),
]

# ── assemble generated list ───────────────────────────────────────────────────

_GENERATED_ITEMS = [
    (_ELECTRONICS_NAMES, "Electronics", 21, 29.99, 199.99),
    (_CLOTHING_NAMES,    "Clothing",    41, 12.99, 109.99),
    (_BOOKS_NAMES,       "Books",       61,  9.99,  54.99),
    (_HOME_NAMES,        "Home",        81, 14.99,  99.99),
    (_SPORTS_NAMES,      "Sports",     101,  5.99, 299.99),
    (_KITCHEN_NAMES,     "Kitchen",    201,  4.99, 249.99),
    (_BEAUTY_NAMES,      "Beauty",     301,  3.99, 149.99),
    (_OFFICE_NAMES,      "Office",     401,  2.99,  99.99),
]

_generated: list[dict] = []
import random as _random
_random.seed(42)

for _names, _cat, _start_idx, _min_price, _max_price in _GENERATED_ITEMS:
    for i, (name, desc) in enumerate(_names):
        pid = f"P{_start_idx + i:03d}"
        price = Decimal(str(round(_random.uniform(_min_price, _max_price), 2)))
        stock = _random.randint(5, 150)
        _generated.append({
            "productId": pid,
            "name": name,
            "category": _cat,
            "price": price,
            "stock": stock,
            "description": desc,
        })

PRODUCTS = _BASE_PRODUCTS + _generated

ORDERS = [
    {"orderId": "O001", "customerId": "C001", "productId": "P001", "quantity": 1, "status": "delivered", "totalPrice": Decimal("79.99"), "createdAt": "2024-01-05T10:00:00Z"},
    {"orderId": "O002", "customerId": "C001", "productId": "P011", "quantity": 2, "status": "delivered", "totalPrice": Decimal("69.98"), "createdAt": "2024-01-12T14:30:00Z"},
    {"orderId": "O003", "customerId": "C001", "productId": "P006", "quantity": 1, "status": "shipped", "totalPrice": Decimal("89.99"), "createdAt": "2024-02-01T09:15:00Z"},
    {"orderId": "O004", "customerId": "C001", "productId": "P017", "quantity": 1, "status": "pending", "totalPrice": Decimal("49.99"), "createdAt": "2024-02-20T16:45:00Z"},
    {"orderId": "O005", "customerId": "C001", "productId": "P003", "quantity": 2, "status": "delivered", "totalPrice": Decimal("79.98"), "createdAt": "2024-03-08T11:00:00Z"},
    {"orderId": "O006", "customerId": "C002", "productId": "P002", "quantity": 1, "status": "delivered", "totalPrice": Decimal("129.99"), "createdAt": "2024-01-08T08:00:00Z"},
    {"orderId": "O007", "customerId": "C002", "productId": "P012", "quantity": 1, "status": "delivered", "totalPrice": Decimal("44.99"), "createdAt": "2024-01-25T13:00:00Z"},
    {"orderId": "O008", "customerId": "C002", "productId": "P018", "quantity": 1, "status": "shipped", "totalPrice": Decimal("89.99"), "createdAt": "2024-02-14T10:30:00Z"},
    {"orderId": "O009", "customerId": "C002", "productId": "P009", "quantity": 3, "status": "pending", "totalPrice": Decimal("209.97"), "createdAt": "2024-03-01T15:00:00Z"},
    {"orderId": "O010", "customerId": "C002", "productId": "P016", "quantity": 2, "status": "delivered", "totalPrice": Decimal("59.98"), "createdAt": "2024-03-10T09:00:00Z"},
    {"orderId": "O011", "customerId": "C003", "productId": "P008", "quantity": 5, "status": "delivered", "totalPrice": Decimal("99.95"), "createdAt": "2024-01-15T12:00:00Z"},
    {"orderId": "O012", "customerId": "C003", "productId": "P015", "quantity": 1, "status": "delivered", "totalPrice": Decimal("14.99"), "createdAt": "2024-02-03T14:00:00Z"},
    {"orderId": "O013", "customerId": "C003", "productId": "P004", "quantity": 1, "status": "shipped", "totalPrice": Decimal("59.99"), "createdAt": "2024-02-18T11:30:00Z"},
    {"orderId": "O014", "customerId": "C003", "productId": "P019", "quantity": 2, "status": "pending", "totalPrice": Decimal("49.98"), "createdAt": "2024-03-05T16:00:00Z"},
    {"orderId": "O015", "customerId": "C003", "productId": "P020", "quantity": 1, "status": "delivered", "totalPrice": Decimal("19.99"), "createdAt": "2024-03-12T10:00:00Z"},
]


def load_all():
    products_table = get_table("Products")
    orders_table = get_table("Orders")

    for product in PRODUCTS:
        products_table.put_item(Item=product)

    for order in ORDERS:
        orders_table.put_item(Item=order)

    return {"products": len(PRODUCTS), "orders": len(ORDERS)}


def wipe_all():
    products_table = get_table("Products")
    orders_table = get_table("Orders")

    products = products_table.scan(ProjectionExpression="productId")["Items"]
    for p in products:
        products_table.delete_item(Key={"productId": p["productId"]})

    orders = orders_table.scan(ProjectionExpression="orderId, customerId")["Items"]
    for o in orders:
        orders_table.delete_item(Key={"orderId": o["orderId"], "customerId": o["customerId"]})

    return {"deleted_products": len(products), "deleted_orders": len(orders)}
